# Generated by Django 4.0.3 on 2022-04-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercises',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='day_name',
        ),
        migrations.AlterField(
            model_name='training',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='pace_of_exercise',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
