# Generated by Django 4.0.4 on 2022-04-11 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_exercises_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveIntegerField()),
                ('reps', models.PositiveIntegerField()),
                ('reps_unit', models.CharField(choices=[('RE', 'Reps'), ('SE', 'Seconds'), ('UF', 'Until Failure')], max_length=2)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('total_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('weight_unit', models.CharField(choices=[('KG', 'Kg'), ('BW', 'Body Weight')], max_length=2)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.dayname')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.exercises')),
            ],
        ),
    ]
