# Generated by Django 4.0.4 on 2022-04-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_workoutset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplan',
            name='reps_unit',
            field=models.CharField(choices=[('Reps', 'Reps'), ('Seconds', 'Seconds'), ('Until Failure', 'Until Failure')], max_length=25),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='reps_unit',
            field=models.CharField(choices=[('Reps', 'Reps'), ('Seconds', 'Seconds'), ('Until Failure', 'Until Failure')], max_length=25),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='weight_unit',
            field=models.CharField(choices=[('Kg', 'Kg'), ('Body Weight', 'Body Weight')], max_length=15),
        ),
    ]
