# Generated by Django 4.0.4 on 2022-04-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_alter_workoutset_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='trainingplan',
            options={'ordering': ['training']},
        ),
        migrations.AlterField(
            model_name='exercises',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
