# Generated by Django 4.0.4 on 2022-04-19 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_trainingplanname_alter_trainingplan_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutset',
            name='date',
            field=models.DateField(blank=True, default='2022-04-19', null=True),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='day',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='training.dayname'),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='total_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
