# Generated by Django 4.0.4 on 2022-04-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_alter_workoutset_date_alter_workoutset_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutset',
            name='date',
            field=models.DateField(default='2022-04-19'),
        ),
    ]
