# Generated by Django 4.0.4 on 2022-04-19 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0014_alter_workoutset_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingplan',
            old_name='training_plan_nb',
            new_name='training_plan_name',
        ),
    ]
