# Generated by Django 4.0.4 on 2022-04-19 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0015_rename_training_plan_nb_trainingplan_training_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplanname',
            name='owner',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
