# Generated by Django 4.0.4 on 2022-07-19 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0016_trainingplanname_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='training_plan_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='training.trainingplanname'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='training_plan_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingplanname'),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='date',
            field=models.DateField(default='2022-07-19'),
        ),
    ]
