# Generated by Django 4.0.4 on 2022-07-20 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0017_training_training_plan_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutset',
            name='training_plan_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='training.trainingplanname'),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='date',
            field=models.DateField(default='2022-07-20'),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='day',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='training.dayname'),
        ),
    ]
