# Generated by Django 4.0.4 on 2022-07-25 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0018_workoutset_training_plan_name_alter_workoutset_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutset',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='date',
            field=models.DateField(default='2022-07-25'),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='training.dayname'),
        ),
    ]
