# Generated by Django 4.0.4 on 2022-10-13 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0019_workoutset_order_alter_workoutset_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutset',
            options={'ordering': ['date', 'order']},
        ),
        migrations.AddField(
            model_name='workoutset',
            name='training',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to='training.training'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='date',
            field=models.DateField(default='2022-10-13'),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='day',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='training.dayname'),
        ),
    ]
